# backend:
  # Use netlify identity as backend
  # name: git-gateway
  # branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo:  MartijnNieuwenhuizen/brainmaster-method 
backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images"
public_folder: "/assets/images"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Blog"
    name: "blog"
    folder: "src/blog"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      # - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      # - { label: "Permalink", name: "permalink", widget: "hidden", default: "/foo/bar/" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/mainNav.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: true
            collapsed: true
            fields:
              - { label: Title, name: label, widget: string }
              - { label: URL, name: url, widget: string }